apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80  # The port your service will be exposed on
      targetPort: 3000  # The port your application runs on
  type: LoadBalancer  # Change to ClusterIP if not exposing externally
